name = "anthropic2openai"
main = "src/index.js"
compatibility_date = "2025-07-19"

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
# Default OpenAI API URL
OPENAI_API_URL = "https://api.openai.com/v1/chat/completions"
# Default OpenAI model to use regardless of what's requested from Anthropic
OPENAI_MODEL_ID = "gpt-4o"
# Set to "true" to require API key authentication, "false" to disable
REQUIRE_AUTH = "true"

# Use wrangler secret put OPENAI_API_KEY to set your OpenAI API key
# Command: npx wrangler secret put OPENAI_API_KEY

# Use wrangler secret put ANTHROPIC_API_KEYS to set allowed API keys (comma-separated)
# Command: npx wrangler secret put ANTHROPIC_API_KEYS
# Example: "sk-ant-api03-xxx,sk-ant-api03-yyy" (multiple keys separated by comma)
